name: note_app
description: A simple note app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  feather_icons: ^1.2.0
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  package_info_plus: ^4.0.2
  shared_preferences: ^2.2.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  http: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/